name: Static analysis

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.3', '8.4', '8.5']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: ${{ matrix.php }}

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.3', '8.4', '8.5']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, memcached, apcu
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          composer require --dev --no-update psalm/phar:3.16
          composer update --no-interaction --prefer-dist

      - name: Psalm
        run: |
          ./vendor/bin/psalm.phar --version
          ./vendor/bin/psalm.phar --output-format=github --no-progress --show-info=false --stats
